import { type SchoolIncidentData, convertToDisplayFormat, type IncidentData } from "./types"

// Sample CSV data based on the structure provided
const sampleCsvData: SchoolIncidentData[] = [
  {
    uid: "1",
    nces_school_id: "170993000122",
    school_name: "Lincoln Elementary School",
    nces_district_id: "1709930",
    district_name: "Springfield School District 186",
    date: "2024-01-15",
    school_year: "2023-24",
    year: 2024,
    time: "10:30 AM",
    day_of_week: "Monday",
    city: "Springfield",
    state: "Illinois",
    school_type: "Elementary",
    enrollment: 450,
    killed: 0,
    injured: 2,
    casualties: 2,
    shooting_type: "Accidental discharge",
    age_shooter1: 16,
    gender_shooter1: "Male",
    race_ethnicity_shooter1: "White",
    shooter_relationship1: "Student",
    shooter_deceased1: false,
    white: 200,
    black: 150,
    hispanic: 80,
    asian: 15,
    american_indian_alaska_native: 3,
    hawaiian_native_pacific_islander: 1,
    two_or_more: 1,
    resource_officer: true,
    weapon: "Handgun",
    weapon_source: "Unknown",
    lat: 39.7817,
    long: -89.6501,
    staffing: 35,
    low_grade: "K",
    high_grade: "5",
    lunch: "Free/Reduced: 65%",
    county: "Sangamon",
    state_fips: "17",
    county_fips: "167",
    ulocale: "City: Large",
  },
  {
    uid: "2",
    nces_school_id: "170993001234",
    school_name: "Roosevelt High School",
    nces_district_id: "1709931",
    district_name: "Chicago Public Schools",
    date: "2024-02-03",
    school_year: "2023-24",
    year: 2024,
    time: "2:15 PM",
    day_of_week: "Friday",
    city: "Chicago",
    state: "Illinois",
    school_type: "High School",
    enrollment: 1200,
    killed: 1,
    injured: 4,
    casualties: 5,
    shooting_type: "Targeted shooting",
    age_shooter1: 17,
    gender_shooter1: "Male",
    race_ethnicity_shooter1: "Black",
    shooter_relationship1: "Student",
    shooter_deceased1: false,
    white: 300,
    black: 600,
    hispanic: 250,
    asian: 40,
    american_indian_alaska_native: 5,
    hawaiian_native_pacific_islander: 2,
    two_or_more: 3,
    resource_officer: true,
    weapon: "Handgun",
    weapon_source: "Brought from home",
    lat: 41.8781,
    long: -87.6298,
    staffing: 85,
    low_grade: "9",
    high_grade: "12",
    lunch: "Free/Reduced: 78%",
    county: "Cook",
    state_fips: "17",
    county_fips: "031",
    ulocale: "City: Large",
  },
  {
    uid: "3",
    nces_school_id: "060570001122",
    school_name: "University of California, Los Angeles",
    nces_district_id: "0605700",
    district_name: "UC System",
    date: "2024-01-28",
    school_year: "2023-24",
    year: 2024,
    time: "11:45 PM",
    day_of_week: "Sunday",
    city: "Los Angeles",
    state: "California",
    school_type: "University",
    enrollment: 31000,
    killed: 0,
    injured: 1,
    casualties: 1,
    shooting_type: "Unintentional shooting",
    age_shooter1: 20,
    gender_shooter1: "Male",
    race_ethnicity_shooter1: "Hispanic",
    shooter_relationship1: "Student",
    shooter_deceased1: false,
    white: 12000,
    black: 3000,
    hispanic: 8000,
    asian: 6000,
    american_indian_alaska_native: 200,
    hawaiian_native_pacific_islander: 100,
    two_or_more: 1700,
    resource_officer: true,
    weapon: "Handgun",
    weapon_source: "Unknown",
    lat: 34.0522,
    long: -118.2437,
    staffing: 2500,
    low_grade: "Undergraduate",
    high_grade: "Graduate",
    lunch: "N/A",
    county: "Los Angeles",
    state_fips: "06",
    county_fips: "037",
    ulocale: "City: Large",
  },
  {
    uid: "4",
    nces_school_id: "480570002233",
    school_name: "Washington Middle School",
    nces_district_id: "4805700",
    district_name: "Austin Independent School District",
    date: "2024-03-10",
    school_year: "2023-24",
    year: 2024,
    time: "1:20 PM",
    day_of_week: "Wednesday",
    city: "Austin",
    state: "Texas",
    school_type: "Middle School",
    enrollment: 800,
    killed: 2,
    injured: 8,
    casualties: 10,
    shooting_type: "Indiscriminate shooting",
    age_shooter1: 14,
    gender_shooter1: "Male",
    race_ethnicity_shooter1: "White",
    shooter_relationship1: "Student",
    shooter_deceased1: true,
    deceased_notes1: "Suicide",
    white: 320,
    black: 120,
    hispanic: 300,
    asian: 50,
    american_indian_alaska_native: 8,
    hawaiian_native_pacific_islander: 1,
    two_or_more: 1,
    resource_officer: false,
    weapon: "Rifle",
    weapon_source: "Brought from home",
    lat: 30.2672,
    long: -97.7431,
    staffing: 55,
    low_grade: "6",
    high_grade: "8",
    lunch: "Free/Reduced: 55%",
    county: "Travis",
    state_fips: "48",
    county_fips: "453",
    ulocale: "City: Large",
  },
  {
    uid: "5",
    nces_school_id: "120570003344",
    school_name: "Jefferson Elementary",
    nces_district_id: "1205700",
    district_name: "Miami-Dade County Public Schools",
    date: "2024-02-20",
    school_year: "2023-24",
    year: 2024,
    time: "9:15 AM",
    day_of_week: "Tuesday",
    city: "Miami",
    state: "Florida",
    school_type: "Elementary",
    enrollment: 650,
    killed: 0,
    injured: 3,
    casualties: 3,
    shooting_type: "Targeted shooting",
    age_shooter1: 25,
    gender_shooter1: "Male",
    race_ethnicity_shooter1: "Hispanic",
    shooter_relationship1: "Former employee",
    shooter_deceased1: false,
    white: 100,
    black: 200,
    hispanic: 320,
    asian: 25,
    american_indian_alaska_native: 2,
    hawaiian_native_pacific_islander: 1,
    two_or_more: 2,
    resource_officer: true,
    weapon: "Handgun",
    weapon_source: "Legally owned",
    lat: 25.7617,
    long: -80.1918,
    staffing: 45,
    low_grade: "K",
    high_grade: "5",
    lunch: "Free/Reduced: 85%",
    county: "Miami-Dade",
    state_fips: "12",
    county_fips: "086",
    ulocale: "City: Large",
  },
]

export async function loadCsvData(): Promise<IncidentData[]> {
  // In a real implementation, this would fetch from a CSV file or API
  // For now, we'll use the sample data
  return sampleCsvData.map(convertToDisplayFormat)
}

export async function loadIncidentsFromCSV(): Promise<IncidentData[]> {
  return loadCsvData()
}

export function getCsvData(): SchoolIncidentData[] {
  return sampleCsvData
}
